### ISSUE TITLE
Реализовать проект

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/just-copy#123]
Требуется реализовать проект. С разделением на необходимые компоненты по смыслу.

Чем точнее и больше деталей будет отражено с макета, тем больше баллов.
Кроме того, необходимо добавить несколько базовых страниц для логичных переходов и использованием общих футера и шапки. Для данного макета необходимо сделать страницу при клике с карточкой товара, карточка плитки, карточка новости. Добавление в корзину. Корзина и товары хранить в redux. Корзина также сохраняется в localStorage.

Макет можно взять другой (куча вариантов на pinterest, behance, dribbble - везде для поиска нужна регистрация)
Макет необходимо согласовать со мной!

Макет который можно начать делать:

![](https://i.pinimg.com/564x/02/51/23/025123a4c64aa88fbadb6676cad9aa83.jpg)

**Comment by reznikovkg** [comment]
<img width="762" alt="image" src="https://github.com/reznikovkg/just-copy/assets/36205504/4cce82bd-212a-4d0e-9820-a75b3b91bd53">
Переделать. Хотя бы как-то должно соответствовать макету

**Comment by helenka20** [comment]
Поиск исправила. Высылаю пдф
[Попова Елена сайт.pdf](https://github.com/reznikovkg/just-copy/files/14229975/default.pdf)

**Comment by reznikovkg** [comment]
Сделайте более похоже. Сейчас вы выровняли размеры. Границы должны быть общие. У кнопки не должно быть своих границ вообще.

**Comment by helenka20** [comment]
Исправила
[Попова Елена сайт.pdf](https://github.com/reznikovkg/just-copy/files/14231887/default.pdf)
